### ISSUE TITLE
Running this module fails if version input is an integer and puppet > 4

### ISSUE THREAD

**Issue by 030** [schrepfler/puppet-jdk_oracle#7]
https://github.com/schrepfler/puppet-jdk_oracle/blob/master/manifests/init.pp#L51

hiera
```
jdk_oracle::version: 8
```

results in

```
Error: Evaluation Error: Error while evaluating a Function Call, Unsupported version: 8.  Implement me? at /etc/puppet/environments/production/modules/jdk_oracle/manifests/init.pp:27:13 on node localhost.localdomain
```

In my opinion stdlib should be used to validate the input and the check should be validate_integer as 8 is an integer and not a string. If the latter is implement then the '7' and '8' in the switch need to be transformed to integer, i.e. 7 and 8.

**Comment by schrepfler** [comment]
I can live with a version being a string. Does it cause you any issues if not used like that?

**Comment by 030** [comment]
8 is an integer. I will create a PR.

**Comment by schrepfler** [comment]
Merged to master, let's make sure the compatibility breakage is apparent. How to people notice there's a new version of modules?
