### ISSUE TITLE
Enhancement: hiera lookup not required as this is default since puppet 3

### ISSUE THREAD

**Issue by 030** [schrepfler/puppet-jdk_oracle#8]
```
  $version      = hiera('jdk_oracle::version',        '8' ),
  $arch         = hiera('jdk_oracle::arch',           'x64' ),
  $install_dir  = hiera('jdk_oracle::install_dir',    '/usr/java' ),
  $tmp_dir      = hiera('jdk_oracle::tmp_dir',        '/tmp' ),
  $use_cache    = hiera('jdk_oracle::use_cache',      false ),
  $cache_source = 'puppet:///modules/jdk_oracle/',
  $jce          = hiera('jdk_oracle::jce',            false ),
  $default_java = hiera('jdk_oracle::default_java',   true),
```

could be changed to

```
  $version      =   8 ,
  $arch         =  'x64' ,
  $install_dir  =   '/usr/java',
  $tmp_dir      =  '/tmp',
  $use_cache    =  false ,
  $cache_source = 'puppet:///modules/jdk_oracle/',
  $jce          = false,
  $default_java = true,
```

**Comment by schrepfler** [comment]
I didn't know this, good change but what are the implications on compatibility though? How would the module behave pre-puppet 3? How would the version be passed?

**Comment by 030** [comment]
That is a good question. Users that use an old version of Puppet are restricted to use 0.9.7 and if puppet4 is used then users could use newer version. We could also check if the version of puppet is 4. 
```
if !($::puppetversion > '4.0.0') {
    fail("Incompatible with \"${::puppetversion}\". Greater than: \"${supported_puppetversion}\" is required")
}
```

**Comment by schrepfler** [comment]
I guess this is philosophical, my thoughts are that compatibility should trump the reduction in code. What are your thoughts, should we leave it to do the hiera lookup anyhow?

**Comment by 030** [comment]
Tested using the master branch:

hiera
```
jdk_oracle::version: 6
```

the default 8 is overwritten (without using hiera() lookup function)
```
Error: Evaluation Error: Error while evaluating a Function Call, Unsupported version: 6. Supported versions are 7 and 8 at ../jdk_oracle/manifests/init.pp:62:7 on node localhost
```

**Comment by 030** [comment]
I will have to do some more research regarding the compatibility whether it is seen as a minor, intermediate or major release.

**Comment by schrepfler** [comment]
I don't think we've ever supported 6, is that the problem? How would you propose we move forward, bump major version and have changelog with entry stating breaking change?

**Comment by 030** [comment]
Sounds like a good idea. If people would like to upgrade then they have to check the changelog and then they will be informed.

**Comment by schrepfler** [comment]
So, just to be clear, if we have this change puppet 3 support goes down the drain, there's no way we can make it compatible with both?

**Comment by schrepfler** [comment]
I've  noticed post publishing that only the version got actually changed in the commit?

**Comment by 030** [comment]
People who would like to use an older Puppet version should not update

**Comment by schrepfler** [comment]
I've managed to install the module on both puppet 3 and puppet 4 boxes with a simple import statement. My guess is this will fail only if somebody is explicitly setting any of the parameters or injecting them via hiera? I'm of the thought we should leave the hiera lookup syntax for all variables, I think that will make it puppet3 compatible yet still work with puppet4.
It's a minor nuisance for us to have these 5-6 lines of code but more people will be able to continue using the module?

**Comment by schrepfler** [comment]
Needs confirmation from people using the module using hiera.
