### ISSUE TITLE
Enhancement: puppet forge downloads and version button

### ISSUE THREAD

**Issue by 030** [schrepfler/puppet-jdk_oracle#9]

**Comment by 030** [comment]
I would like to push a branch to this repo, but that is not allowed:

```
ERROR: Permission to schrepfler/puppet-jdk_oracle.git denied to 030.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by schrepfler** [comment]
Hi 030,
Thanks for the attempt at contribution! I think the canonical way to contribute on GitHub is to clone the repository to your repo, commit to it and then file a merge request. Give it a go, it's very simple!

**Comment by 030** [comment]
I forget that. Now I have forked the repo and created a PR
